package orm;
// Generated 26 nov 2024 13:33:18 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Equipo generated by hbm2java
 */
public class Equipo implements java.io.Serializable {

	private int idEquipo;
	private String nombre;
	private String localidad;
	private String pais;
	private String nombreCorto;
	private Set jugadors = new HashSet(0);
	private Set partidosForIdEquipoVisitante = new HashSet(0);
	private Set partidosForIdEquipoLocal = new HashSet(0);

	public Equipo() {
	}

	public Equipo(int idEquipo) {
		this.idEquipo = idEquipo;
	}

	public Equipo(int idEquipo, String nombre, String localidad, String pais, String nombreCorto, Set jugadors,
			Set partidosForIdEquipoVisitante, Set partidosForIdEquipoLocal) {
		this.idEquipo = idEquipo;
		this.nombre = nombre;
		this.localidad = localidad;
		this.pais = pais;
		this.nombreCorto = nombreCorto;
		this.jugadors = jugadors;
		this.partidosForIdEquipoVisitante = partidosForIdEquipoVisitante;
		this.partidosForIdEquipoLocal = partidosForIdEquipoLocal;
	}

	public int getIdEquipo() {
		return this.idEquipo;
	}

	public void setIdEquipo(int idEquipo) {
		this.idEquipo = idEquipo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getLocalidad() {
		return this.localidad;
	}

	public void setLocalidad(String localidad) {
		this.localidad = localidad;
	}

	public String getPais() {
		return this.pais;
	}

	public void setPais(String pais) {
		this.pais = pais;
	}

	public String getNombreCorto() {
		return this.nombreCorto;
	}

	public void setNombreCorto(String nombreCorto) {
		this.nombreCorto = nombreCorto;
	}

	public Set getJugadors() {
		return this.jugadors;
	}

	public void setJugadors(Set jugadors) {
		this.jugadors = jugadors;
	}

	public Set getPartidosForIdEquipoVisitante() {
		return this.partidosForIdEquipoVisitante;
	}

	public void setPartidosForIdEquipoVisitante(Set partidosForIdEquipoVisitante) {
		this.partidosForIdEquipoVisitante = partidosForIdEquipoVisitante;
	}

	public Set getPartidosForIdEquipoLocal() {
		return this.partidosForIdEquipoLocal;
	}

	public void setPartidosForIdEquipoLocal(Set partidosForIdEquipoLocal) {
		this.partidosForIdEquipoLocal = partidosForIdEquipoLocal;
	}

}
