package orm;
// Generated 26 nov 2024 13:33:18 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Jugador generated by hbm2java
 */
public class Jugador implements java.io.Serializable {

	private int idJugador;
	private Equipo equipo;
	private String nombre;
	private String apellidos;
	private Integer alturaCm;
	private Integer edad;
	private String nacionalidad;
	private Set datosjugadorpartidos = new HashSet(0);

	public Jugador() {
	}

	public Jugador(int idJugador) {
		this.idJugador = idJugador;
	}

	public Jugador(int idJugador, Equipo equipo, String nombre, String apellidos, Integer alturaCm, Integer edad,
			String nacionalidad, Set datosjugadorpartidos) {
		this.idJugador = idJugador;
		this.equipo = equipo;
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.alturaCm = alturaCm;
		this.edad = edad;
		this.nacionalidad = nacionalidad;
		this.datosjugadorpartidos = datosjugadorpartidos;
	}

	public int getIdJugador() {
		return this.idJugador;
	}

	public void setIdJugador(int idJugador) {
		this.idJugador = idJugador;
	}

	public Equipo getEquipo() {
		return this.equipo;
	}

	public void setEquipo(Equipo equipo) {
		this.equipo = equipo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	public Integer getAlturaCm() {
		return this.alturaCm;
	}

	public void setAlturaCm(Integer alturaCm) {
		this.alturaCm = alturaCm;
	}

	public Integer getEdad() {
		return this.edad;
	}

	public void setEdad(Integer edad) {
		this.edad = edad;
	}

	public String getNacionalidad() {
		return this.nacionalidad;
	}

	public void setNacionalidad(String nacionalidad) {
		this.nacionalidad = nacionalidad;
	}

	public Set getDatosjugadorpartidos() {
		return this.datosjugadorpartidos;
	}

	public void setDatosjugadorpartidos(Set datosjugadorpartidos) {
		this.datosjugadorpartidos = datosjugadorpartidos;
	}
	
	@Override
	public String toString() {
		String datos = "Nombre: " + getNombre() + " - Apellidos: " + getApellidos() + " - Edad: " + getEdad() + " - Nacionalidad: " + getNacionalidad() + " - Altura: " + getAlturaCm() + "cm - ID Jugador: " + getIdJugador() + " - ID Equipo: " + equipo.getIdEquipo();
		return datos;
	}
}
