package orm;
// Generated 26 nov 2024 13:22:35 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Partido generated by hbm2java
 */
public class Partido implements java.io.Serializable {

	private int idPartido;
	private Equipo equipoByIdEquipoVisitante;
	private Equipo equipoByIdEquipoLocal;
	private Integer puntosLocal;
	private Integer puntosVisitante;
	private Set datosjugadorpartidos = new HashSet(0);

	public Partido() {
	}

	public Partido(int idPartido) {
		this.idPartido = idPartido;
	}

	public Partido(int idPartido, Equipo equipoByIdEquipoVisitante, Equipo equipoByIdEquipoLocal, Integer puntosLocal,
			Integer puntosVisitante, Set datosjugadorpartidos) {
		this.idPartido = idPartido;
		this.equipoByIdEquipoVisitante = equipoByIdEquipoVisitante;
		this.equipoByIdEquipoLocal = equipoByIdEquipoLocal;
		this.puntosLocal = puntosLocal;
		this.puntosVisitante = puntosVisitante;
		this.datosjugadorpartidos = datosjugadorpartidos;
	}

	public int getIdPartido() {
		return this.idPartido;
	}

	public void setIdPartido(int idPartido) {
		this.idPartido = idPartido;
	}

	public Equipo getEquipoByIdEquipoVisitante() {
		return this.equipoByIdEquipoVisitante;
	}

	public void setEquipoByIdEquipoVisitante(Equipo equipoByIdEquipoVisitante) {
		this.equipoByIdEquipoVisitante = equipoByIdEquipoVisitante;
	}

	public Equipo getEquipoByIdEquipoLocal() {
		return this.equipoByIdEquipoLocal;
	}

	public void setEquipoByIdEquipoLocal(Equipo equipoByIdEquipoLocal) {
		this.equipoByIdEquipoLocal = equipoByIdEquipoLocal;
	}

	public Integer getPuntosLocal() {
		return this.puntosLocal;
	}

	public void setPuntosLocal(Integer puntosLocal) {
		this.puntosLocal = puntosLocal;
	}

	public Integer getPuntosVisitante() {
		return this.puntosVisitante;
	}

	public void setPuntosVisitante(Integer puntosVisitante) {
		this.puntosVisitante = puntosVisitante;
	}

	public Set getDatosjugadorpartidos() {
		return this.datosjugadorpartidos;
	}

	public void setDatosjugadorpartidos(Set datosjugadorpartidos) {
		this.datosjugadorpartidos = datosjugadorpartidos;
	}

}
